### ISSUE TITLE
Heroku doesnt deploy app due to python-3.10.2 in runtime.txt.

### ISSUE THREAD

**Issue by Reyzyn** [DebiprasadXD/link-media-scraper-bot#5]
-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     Requested runtime 'python-3.10.2' is not available for this stack (heroku-22).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by Reyzyn** [comment]
It worked with the updated runtime.

**Comment by debiplobi** [comment]
Okay will fix it , btw As heroku planning to remove free tier plan, I am thinking to remove heroku support , what do you say!
