### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by djsaikrishna** [DebiprasadXD/link-media-scraper-bot#7]
always getting proxy error

plz give tutorial  for heroku

thank you.

**Comment by debiplobi** [comment]
Use a rotating proxy, just tap on the deploy on heroku button, and fill the required fields > deploy
Turn on the worker after deployment.

Note : I AM THINKING OF REMOVING DEPLOY TO HEROKU AS IT IS NO MORE FREE

**Comment by djsaikrishna** [comment]
> Use a rotating proxy, just tap on the deploy on heroku button, and fill the required fields > deploy Turn on the worker after deployment.
> 
> Note : I AM THINKING OF REMOVING DEPLOY TO HEROKU AS IT IS NO MORE FREE

Plz make app.koyeb.com tutorial

**Comment by debiplobi** [comment]
Unfortunately, I have just signed up yesterday, don't have an active account of koyeb, so wait a bit, I'll try to make one in future.
Thanks for the suggestions though

**Comment by djsaikrishna** [comment]
> Unfortunately, I have just signed up yesterday, don't have an active account of koyeb, so wait a bit, I'll try to make one in future. Thanks for the suggestions though

I will give u my koyeb active account plz make tut today 
Badly need this can u provide ur telegram bot username

**Comment by debiplobi** [comment]
Drop a dm here
t.me/debnationxd
