### ISSUE TITLE
bunkr downloading not working

### ISSUE THREAD

**Issue by damian2603** [DebiprasadXD/link-media-scraper-bot#9]
when i try to download album with videos, bot scraping all links but cant download it
Im getting this error:
Downloading....mp4
Processing Thumbnail
No video found
expected str, bytes or os.PathLike object, not NoneType

**Comment by debiplobi** [comment]
Maybe that media resource is got deleted from the server.

**Comment by damian2603** [comment]
I can download media manually and also can download with this tool https://github.com/Jules-WinnfieldX/CyberDropDownloader, but there is no upload to telegram function.

**Comment by debiplobi** [comment]
Ok, I have fixed bunkr handler, it is working as for now, test and let me know if you found any bugs
